const bcrypt = require('bcryptjs');

// Pre-hashed passwords for default users (admin123 and student123)
const adminPasswordHash = bcrypt.hashSync('admin123', 10);
const studentPasswordHash = bcrypt.hashSync('student123', 10);

const mockUsers = [
  {
    _id: 'mock_admin_1',
    name: 'TechQuiz Administrator',
    email: 'admin@techquiz.com',
    password: adminPasswordHash,
    role: 'admin',
    department: 'Administration',
    createdAt: new Date(),
  },
  {
    _id: 'mock_student_1',
    name: 'John Doe',
    email: 'student@techquiz.com',
    password: studentPasswordHash,
    role: 'student',
    department: 'Computer Science',
    createdAt: new Date(),
  },
];

const mockQuizzes = [
  {
    _id: 'mock_quiz_1',
    title: 'JavaScript Fundamentals',
    description: 'Test your core understanding of JavaScript closures, scopes, arrays, promises, and async execution.',
    category: 'JavaScript',
    duration: 10,
    passingMarks: 6,
    totalMarks: 10,
    createdBy: 'mock_admin_1',
    isPublished: true,
    createdAt: new Date(),
    questions: [
      {
        _id: 'q1',
        questionText: 'Which keyword is used to declare a variable that is block-scoped and cannot be reassigned?',
        optionA: 'var',
        optionB: 'let',
        optionC: 'const',
        optionD: 'def',
        correctAnswer: 'C',
        marks: 2,
        difficulty: 'Easy',
      },
      {
        _id: 'q2',
        questionText: 'What is the output of: console.log(typeof NaN);',
        optionA: '"number"',
        optionB: '"nan"',
        optionC: '"undefined"',
        optionD: '"object"',
        correctAnswer: 'A',
        marks: 2,
        difficulty: 'Medium',
      },
      {
        _id: 'q3',
        questionText: 'Which of the following is NOT a JavaScript primitive data type?',
        optionA: 'String',
        optionB: 'Boolean',
        optionC: 'Object',
        optionD: 'Symbol',
        correctAnswer: 'C',
        marks: 2,
        difficulty: 'Easy',
      },
      {
        _id: 'q4',
        questionText: 'Which method returns a new array with all elements that pass the test implemented by the provided function?',
        optionA: 'map()',
        optionB: 'filter()',
        optionC: 'reduce()',
        optionD: 'forEach()',
        correctAnswer: 'B',
        marks: 2,
        difficulty: 'Medium',
      },
      {
        _id: 'q5',
        questionText: 'What is the purpose of the Event Loop in JavaScript?',
        optionA: 'To execute async operations in a separate operating system thread.',
        optionB: 'To monitor the Call Stack and Callback Queue, pushing deferred executions to the stack.',
        optionC: 'To optimize DOM painting and UI layouts.',
        optionD: 'To compile Javascript code into machine code.',
        correctAnswer: 'B',
        marks: 2,
        difficulty: 'Hard',
      },
    ],
  },
  {
    _id: 'mock_quiz_2',
    title: 'Python Essentials',
    description: 'Evaluate your knowledge on list comprehensions, decorators, generator yield states, and standard library modules.',
    category: 'Python',
    duration: 15,
    passingMarks: 4,
    totalMarks: 8,
    createdBy: 'mock_admin_1',
    isPublished: true,
    createdAt: new Date(),
    questions: [
      {
        _id: 'pq1',
        questionText: 'What does a generator function return in Python?',
        optionA: 'A list of values',
        optionB: 'An iterator object',
        optionC: 'None',
        optionD: 'A tuple key',
        correctAnswer: 'B',
        marks: 2,
        difficulty: 'Medium',
      },
      {
        _id: 'pq2',
        questionText: 'Which method can be used to add an item to the end of a list in Python?',
        optionA: 'add()',
        optionB: 'append()',
        optionC: 'insert()',
        optionD: 'extend()',
        correctAnswer: 'B',
        marks: 2,
        difficulty: 'Easy',
      },
      {
        _id: 'pq3',
        questionText: 'How are keyword arguments passed into functions captured inside Python parameter lists?',
        optionA: '*args',
        optionB: '**kwargs',
        optionC: '*kwargs',
        optionD: '&args',
        correctAnswer: 'B',
        marks: 2,
        difficulty: 'Medium',
      },
      {
        _id: 'pq4',
        questionText: 'What is the output of: print("hello".find("z"))?',
        optionA: 'False',
        optionB: '-1',
        optionC: 'ValueError',
        optionD: '0',
        correctAnswer: 'B',
        marks: 2,
        difficulty: 'Hard',
      },
    ],
  },
];

const mockAttempts = [];

module.exports = {
  mockUsers,
  mockQuizzes,
  mockAttempts,
};
